apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "*"
    helm:
      releaseName: vault
      values: |
        ui:
          enabled: true
        server:
          dev:
            enabled: false
          dataStorage:
            enabled: true
            size: 2Gi
          standalone:
            enabled: true
            config: |
              listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                tls_disable = "true"
              }
              storage "file" {
                path = "/vault/data"
              }
              ui = true
        injector:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
