apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alerta-server-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alerta-server-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: alerta/server
        property: database_url
    - secretKey: SECRET_KEY
      remoteRef:
        key: alerta/server
        property: secret_key
    - secretKey: ADMIN_USERS
      remoteRef:
        key: alerta/server
        property: admin_users
    - secretKey: ADMIN_KEY
      remoteRef:
        key: alerta/server
        property: admin_key
