apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alerta-postgres-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alerta-postgres-credentials
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: alerta/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: alerta/postgres
        property: password
